name: Hadolint
on: push

jobs:
  hadolint:
    name: Run hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install docker.io
      - run: docker run --rm -i hadolint/hadolint < Dockerfile
